#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  map-underscore-to-camel-case: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#mapper:
#  identity: MYSQL
#  mappers: tk.mybatis.mapper.common.Mapper
#  not-empty: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useSSL=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    hikari:
      connection-test-query: select 1
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: auth
#  redis:
#    database: 1
#    host: redis-dev.vlive.com.cn
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: 1000
#        max-idle: 8
#        min-idle: 2
#    timeout: 5000
platform:
  wx:
    ma:
      miniAppid: wxMiniAppId
      miniSecret: wxMiniAppSecret
    app:
      appid: appId
      secret: appIdSecret
